    // <auto-generated />
#nullable enable

using PodNet.EnumValues;

public static partial class SnakeCasingValueExtensions
{
    /// <summary>
    /// Gets the associated <see cref="ValueAttribute"/> value for the <see cref="SnakeCasing"/> as follows:
    /// <code>
    ///            [FirstCase] = 0 => "first_case"
    ///           [SecondCase] = 1 => "second_case"
    ///                [Third] = 2 => "third"
    ///      [FourthCASEUpper] = 3 => "fourth_case_upper"
    ///
    ///          [(int)] => (int).ToString()
    /// </code>
    /// </summary>
    /// <remarks>Uses <see cref="UndefinedValueHandling.RawValueToString"/> for undefined values.</remarks>
    /// <param name="value">The <see cref="SnakeCasing"/> value.</param>
    /// <returns>A constant, deterministic string value representing the given <paramref name="value"/>.</returns>
    public static string GetValue(this SnakeCasing value)
        => value switch
        {
            SnakeCasing.FirstCase => "first_case",
            SnakeCasing.SecondCase => "second_case",
            SnakeCasing.Third => "third",
            SnakeCasing.FourthCASEUpper => "fourth_case_upper",
            _ => ((int)value).ToString()
        };
}
#nullable restore