// <auto-generated />
#nullable enable

using PodNet.EnumValues;

public static partial class GreetingValueExtensions
{
    /// <summary>
    /// Gets the associated <see cref="FrenchAttribute"/> value for the <see cref="Greeting"/> as follows:
    /// <code>
    ///          [Hi] = 0 => "Salut"
    /// [GoodMorning] = 1 => "Bonjour"
    /// [GoodEvening] = 2 => "Bonsoir"
    ///
    ///           [(int)] => (int).ToString()
    /// </code>
    /// </summary>
    /// <remarks>Uses <see cref="UndefinedValueHandling.RawValueToString"/> for undefined values.</remarks>
    /// <param name="value">The <see cref="Greeting"/> value.</param>
    /// <returns>A constant, deterministic string value representing the given <paramref name="value"/>.</returns>
    public static string GetFrench(this Greeting value)
        => value switch
        {
            Greeting.Hi => "Salut",
            Greeting.GoodMorning => "Bonjour",
            Greeting.GoodEvening => "Bonsoir",
            _ => ((int)value).ToString()
        };
}
#nullable restore
