// <auto-generated />
#nullable enable

using PodNet.EnumValues;

public static partial class GreetingValueExtensions
{
    /// <summary>
    /// Gets the associated <see cref="SpanishAttribute"/> value for the <see cref="Greeting"/> as follows:
    /// <code>
    ///          [Hi] = 0 => "Hola"
    /// [GoodMorning] = 1 => "Buenos días"
    /// [GoodEvening] = 2 => "Buenas noches"
    ///
    ///           [(int)] => (int).ToString()
    /// </code>
    /// </summary>
    /// <remarks>Uses <see cref="UndefinedValueHandling.RawValueToString"/> for undefined values.</remarks>
    /// <param name="value">The <see cref="Greeting"/> value.</param>
    /// <returns>A constant, deterministic string value representing the given <paramref name="value"/>.</returns>
    public static string GetSpanish(this Greeting value)
        => value switch
        {
            Greeting.Hi => "Hola",
            Greeting.GoodMorning => "Buenos días",
            Greeting.GoodEvening => "Buenas noches",
            _ => ((int)value).ToString()
        };
}
#nullable restore
