// <auto-generated />
#nullable enable

using PodNet.EnumValues;

public static partial class SentimentValueExtensions
{
    /// <summary>
    /// Gets the associated <see cref="ValueAttribute"/> value for the <see cref="Sentiment"/> as follows:
    /// <code>
    /// [Unknown] = 0 => 💥 MissingEnumValueException 💥
    ///   [Happy] = 1 => "Green"
    /// [Neutral] = 2 => "Yellow"
    ///     [Sad] = 3 => "Red"
    ///
    ///       [(int)] => (int).ToString()
    /// </code>
    /// </summary>
    /// <remarks>Uses <see cref="UndefinedValueHandling.RawValueToString"/> for undefined values and <see cref="MissingValueHandling.ThrowMissingValueException"/> for missing values.</remarks>
    /// <param name="value">The <see cref="Sentiment"/> value.</param>
    /// <returns>A constant, deterministic string value representing the given <paramref name="value"/>.</returns>
    /// <exception cref="MissingEnumValueException">Thrown when the provided <paramref name="value"/> is declared as a named enum member but has no corresponding marker attribute of type <see cref="ValueAttribute"/> assigned to it.</exception>
    public static string GetValue(this Sentiment value)
        => value switch
        {
            Sentiment.Unknown => throw new MissingEnumValueException(typeof(Sentiment), value),
            Sentiment.Happy => "Green",
            Sentiment.Neutral => "Yellow",
            Sentiment.Sad => "Red",
            _ => ((int)value).ToString()
        };
}
#nullable restore
