// <auto-generated />
#nullable enable

using PodNet.EnumValues;

public static partial class SentimentValueExtensions
{
    /// <summary>
    /// Gets the associated <see cref="ValueAttribute"/> value for the <see cref="Sentiment"/> as follows:
    /// <code>
    ///   [Happy] = 0 => "Green"
    /// [Neutral] = 1 => "Yellow"
    ///     [Sad] = 2 => "Red"
    ///
    ///       [(int)] => (int).ToString()
    /// </code>
    /// </summary>
    /// <remarks>Uses <see cref="UndefinedValueHandling.RawValueToString"/> for undefined values.</remarks>
    /// <param name="value">The <see cref="Sentiment"/> value.</param>
    /// <returns>A constant, deterministic string value representing the given <paramref name="value"/>.</returns>
    public static string GetValue(this Sentiment value)
        => value switch
        {
            Sentiment.Happy => "Green",
            Sentiment.Neutral => "Yellow",
            Sentiment.Sad => "Red",
            _ => ((int)value).ToString()
        };
}
#nullable restore
